#!/bin/bash

cd ~
clear

mkdir /home/josephyu/Downloads
echo "Created Download dir"

cd /home/josephyu/Downloads
git clone https://github.com/JosephZYU/dotfiles.git
echo "Downloaded dotfiles from Github"

cd /home/josephyu/Downloads/dotfiles
cp .aliases .bash_profile .bash_prompt .bashrc ~/
cd ~
echo "created / replaced .aliases .bash_profile .bash_prompt .bashrc in the Home Directory"