#!/bin/bash

cd ~
clear

git clone https://github.com/JosephZYU/dotfiles.git
echo "Downloaded dotfiles from Github into HOME directory"

cd /home/josephyu/dotfiles
chmod +x install.sh
./install.sh /home/josephyu
echo "created / replaced symlinks for .aliases .bash_profile .bash_prompt .bashrc .gitignore in the Home Directory"
